apiVersion: v1
kind: Service
metadata:
  name: admission-controller-svc
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admission-controller
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app.kubernetes.io/component: admission-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admission-controller
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admission-controller
    spec:
      serviceAccountName: admission-controller-webhook-sa
      containers:
        - name: admission-controller
          image: {{ .Values.operatorImage }}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/tidb-admission-controller
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -v=2
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-controller-certs