{{- if .Values.monitor.create }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
  {{- if .Values.rbac.cross_namespace }}
kind: ClusterRole
  {{- else }}
kind: Role
  {{- end }}
metadata:
  {{- if .Values.rbac.cross_namespace }}
  name: {{ template "cluster.name" . }}:monitor
  {{- else }}
  name: {{ template "cluster.name" . }}-monitor
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: monitor
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch"]
  {{- if .Values.rbac.cross_namespace }}
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
  {{- end }}
---
  {{- if .Values.rbac.cross_namespace }}
kind: ClusterRoleBinding
  {{- else }}
kind: RoleBinding
  {{- end }}
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  {{- if .Values.rbac.cross_namespace }}
  name: {{ template "cluster.name" . }}:monitor
  {{- else }}
  name: {{ template "cluster.name" . }}-monitor
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: monitor
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
subjects:
- kind: ServiceAccount
  {{- if .Values.monitor.serviceAccount }}
  name: {{ .Values.monitor.serviceAccount }}
  {{- else }}
  name: {{ template "cluster.name" . }}-monitor
  {{- end }}
  {{- if .Values.rbac.cross_namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  {{- if .Values.rbac.cross_namespace }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  {{- if .Values.rbac.cross_namespace }}
  name: {{ template "cluster.name" . }}:monitor
  {{- else }}
  name: {{ template "cluster.name" . }}-monitor
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- if not .Values.monitor.serviceAccount }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "cluster.name" . }}-monitor
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: monitor
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
{{- end }}
{{- end }}
{{- end }}
