#apiVersion: v1
#data:
#  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVWnV1cUw5WUNjdlhUcVBKckRjWEJYNjB1RURJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekFlRncweE9URXdNall4TURNMk1EQmFGdzB5TURFdwpNalV4TURNMk1EQmFNQ3d4S2pBb0JnTlZCQU1USVdGa2JXbHpjMmx2YmkxamIyNTBjbTlzYkdWeUxYTjJZeTUwClpYTjBMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjBRYW5qcE5tSEEKaTRTRjZWcjIzdHFZRnJaWFZaTlRjYVFkK28rUVVJbVYveXBFdURkdFkreTdvdXNrSG9kUWJ6ZlBxTnVwRVQ0eQpydjl0eDUzUGFxWk5tOGtCZlBzbFVsM2lINHVMWm9jbFRDK0Y0TUllMnR1RWdjM05kdklNMXlKUkNmaVZ6RjYrCkR1OFh3TXpLOHNBK2RpQVo2SWVRMkJROEVWSmNGR0ljUlROeldqTEE1MWVYQ3hKcS9ROWdSVVUwSDM4RGw1bXgKUUl0TzBvbDI5RlRmUEFBRzBmS2lrRys1YStLTTJ5RGs0MlFFUElSSElPSnh3Z1pZQzRTUlE0ZUU1YWJKb2tEawpSN3Y5RDNoVG81Q1ZqdUo4Y0tQZjJzdklZa3BXNFVlMGtsTDdIank4NElLU1lRenlXRHRKTTUyNVJnaTRBZldzClNwV3YrQ29kTEVVQ0F3RUFBYU9CdkRDQnVUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVU1ZGZ2R2VKZ0ZTZWtGUWRabURyVwo0WktsNDBJd1pRWURWUjBSQkY0d1hJSVlZV1J0YVhOemFXOXVMV052Ym5SeWIyeHNaWEl0YzNaamdoMWhaRzFwCmMzTnBiMjR0WTI5dWRISnZiR3hsY2kxemRtTXVkR1Z6ZElJaFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXQKYzNaakxuUmxjM1F1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkZTbjNnWmxkYUQ4amhORDQxV2tPMgpLR1BJdE9iS0xyeENvWHhQVGNqRDlkQlkzdkRHOUJrUitmeTFxRE9DNEhBQkNlMzNyNjlNOEtmOHRubVQvTjBDCmhjVTFmaUYrbXFoYjNiVUJOVytUa3FrR0NQMUxKSzk3USt2aWNadHJXVEt6ajRMMVRQSjRyZTJUR2xCS1VEdDMKQjI5cWF0b25EODFPQ1VXRDVlc2JwZ0RGQzNmeTZHZkk0SldXR0FZRXNhSnEyclBZTVdJcEVidlJubDhTaTJVTQpCT3FlUXIwdUhJT0tEREM4TENGeEFJa1BIeTBxSjgxRTJNaTRCRk1HcjVsMks3TTVjTUdyWHBYMVN6ZXVtTDdkCnV6Z2swM2VuaDhJQU1WVXQraHk0NzJmaHh4Z21waGx1Sy96UGxSOUFUeEJMeHpjbllyV2Z6TnZYSm9ZT2FCZGIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBM1JCcWVPazJZY0NMaElYcFd2YmUycGdXdGxkVmsxTnhwQjM2ajVCUWlaWC9La1M0Ck4yMWo3THVpNnlRZWgxQnZOOCtvMjZrUlBqS3UvMjNIbmM5cXBrMmJ5UUY4K3lWU1hlSWZpNHRtaHlWTUw0WGcKd2g3YTI0U0J6YzEyOGd6WElsRUorSlhNWHI0Tzd4ZkF6TXJ5d0Q1MklCbm9oNURZRkR3UlVsd1VZaHhGTTNOYQpNc0RuVjVjTEVtcjlEMkJGUlRRZmZ3T1htYkZBaTA3U2lYYjBWTjg4QUFiUjhxS1FiN2xyNG96YklPVGpaQVE4CmhFY2c0bkhDQmxnTGhKRkRoNFRscHNtaVFPUkh1LzBQZUZPamtKV080bnh3bzkvYXk4aGlTbGJoUjdTU1V2c2UKUEx6Z2dwSmhEUEpZTzBrem5ibEdDTGdCOWF4S2xhLzRLaDBzUlFJREFRQUJBb0lCQVFDcHF2dk5LVkZ2M1ZRMwp0bi9RTFVJR0RFMENUaTJFRWJ0YTl4ZGtNS05mdGh4TjJNaDY0aDZiaDdnWE9YV2s3WHN2SHRhL0lSZjI0UGVuClhCNmxaSmk2WXo1NkhBWk15K3hYMmtIVDNING9vOXZCYmNOL3VpYkg3UCtqY1ZzbGsrMWFqVkJWMXNNd3hEYTYKRTBVSzZZay9PN0YyR2V4NmdCVVlFckpJd0J0MDRFaWZHTStwblNPL3gxN01obzN0VW9hdzgvV096UlU2Mlorbwp0Mm9WVHlMTnU3R3BhWVVRa3hOOHZML1IwdWo4bXY3Z2VyMWNBMmwrUDJVb1dzZmM3MG42dHNyRVJaRmd6VmNCClhCT3FpOTBzRUxoNEZ0M0xPZjN0Z2NBYXBtSHU3UDNDMnlEeEd3YTRtNTZ5RmJ6RTNMN29XK3FLOUhsV1hVT0sKYjkrQWZyTlJBb0dCQU85RmcwNkE4QjJCSDVuSnhyTEZkRTl5bHN1UEZ4RWhlMldzR1QyMjAxM3B0MWluMVZnLwpuMXRPMzJYZlgrcFZ1dUpaTnpRTVpSQWE5YnJaZVIxeTl6NEh0YW16dGJZRjRVK3lkbmgrbFlHVlNESU5FWW5ECk9ZRTRyRjdERTNabmNqRkJNcGpwUEpia0JHcU1CN3VEanF3M3hOckdrM1BRQmZMWmEvRW5NRHkzQW9HQkFPeUYKQnNCQm84VXhCZFVqdWVDY25PNVZhNjdDaUdlNnhCcFY5aHlWN1BvZ2ZhaWxyZTVCOXZPb2prOU8xUENOUVlVZwphYWd6elc5MGhZNzcyWFBjclBDQUI0Nkx6UHpVbVFjUlkzZWNjZTlLZkErU1RSYWdYRjBVS05TK2RoQ2FSa09YCmtoQ0lML29LMks0RlhNanI5WXdvQ0R1V0JhdkEyRVZWWEJuUitWcmpBb0dCQU9aYkh5SmFRbEcxZWEzK3M3eHoKR3hwTjhOM0RRZXJ0T0RiWGJHbWM5WHVKd2ttcE0xM0Z5dThHVFU5dnNaRVN2bHlpbGVJWE9NazdtMjRyWjA0eAoyOVN0YVhrYkdndEhOL2Naa3JOSTh6a1Jkck14SDd4bzVwa0E3ZnBCaHlCTVVZVVlCdFZ1WHpYS0NuSmxwQ0FrCmRSeGFpTHd6eDh3TTcxMHhjNWwxS0J5YkFvR0FRTVg5bjFGYXBIcFVlcGFhSlNVKzVSYUhzd2liaXF6Zlg4Y0MKNjdremVSekV6UmJ5bHptQmhDRTVPQWNDMGc0ZFQzUWMrMitVWjEybDVnNmE4dHdRa0p5L2RRNWNTVEYvNXl1Zgo3Zlh1VGZZOEc1ZVpmUVRWeHJmcXByaXlaTUdiVkkrQjlQMFhCb2RKNS82WDluNklkS1hSKzErT2xnYnVNNjY0CjFtbG12TGtDZ1lCS2xHV09QRUpkUzRYQ3J6N1FaT0JGOU5YRUFSSmExa2I0a3BOOTY0VEdCRFVqZTliMzVmRDgKVlh1TVdOeVptbExsT1BFaTJONGVVb0Z5cHQrVXpPeEp1OVNTMzJCOEJsVWxFeVRJaE1xUkRwZkQzWTl2Uy9oOQpLMFk3enRlRlYxY0tIS1ljaFhSM3pmNU4wdEZ3SWs0RU1ReVpIYzd5SW9aMjBuK2xHTDQ0OUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
#kind: Secret
#metadata:
#  annotations:
#    kubectl.kubernetes.io/last-applied-configuration: |
#      {"apiVersion":"v1","data":{"cert.pem":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVWnV1cUw5WUNjdlhUcVBKckRjWEJYNjB1RURJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekFlRncweE9URXdNall4TURNMk1EQmFGdzB5TURFdwpNalV4TURNMk1EQmFNQ3d4S2pBb0JnTlZCQU1USVdGa2JXbHpjMmx2YmkxamIyNTBjbTlzYkdWeUxYTjJZeTUwClpYTjBMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjBRYW5qcE5tSEEKaTRTRjZWcjIzdHFZRnJaWFZaTlRjYVFkK28rUVVJbVYveXBFdURkdFkreTdvdXNrSG9kUWJ6ZlBxTnVwRVQ0eQpydjl0eDUzUGFxWk5tOGtCZlBzbFVsM2lINHVMWm9jbFRDK0Y0TUllMnR1RWdjM05kdklNMXlKUkNmaVZ6RjYrCkR1OFh3TXpLOHNBK2RpQVo2SWVRMkJROEVWSmNGR0ljUlROeldqTEE1MWVYQ3hKcS9ROWdSVVUwSDM4RGw1bXgKUUl0TzBvbDI5RlRmUEFBRzBmS2lrRys1YStLTTJ5RGs0MlFFUElSSElPSnh3Z1pZQzRTUlE0ZUU1YWJKb2tEawpSN3Y5RDNoVG81Q1ZqdUo4Y0tQZjJzdklZa3BXNFVlMGtsTDdIank4NElLU1lRenlXRHRKTTUyNVJnaTRBZldzClNwV3YrQ29kTEVVQ0F3RUFBYU9CdkRDQnVUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVU1ZGZ2R2VKZ0ZTZWtGUWRabURyVwo0WktsNDBJd1pRWURWUjBSQkY0d1hJSVlZV1J0YVhOemFXOXVMV052Ym5SeWIyeHNaWEl0YzNaamdoMWhaRzFwCmMzTnBiMjR0WTI5dWRISnZiR3hsY2kxemRtTXVkR1Z6ZElJaFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXQKYzNaakxuUmxjM1F1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkZTbjNnWmxkYUQ4amhORDQxV2tPMgpLR1BJdE9iS0xyeENvWHhQVGNqRDlkQlkzdkRHOUJrUitmeTFxRE9DNEhBQkNlMzNyNjlNOEtmOHRubVQvTjBDCmhjVTFmaUYrbXFoYjNiVUJOVytUa3FrR0NQMUxKSzk3USt2aWNadHJXVEt6ajRMMVRQSjRyZTJUR2xCS1VEdDMKQjI5cWF0b25EODFPQ1VXRDVlc2JwZ0RGQzNmeTZHZkk0SldXR0FZRXNhSnEyclBZTVdJcEVidlJubDhTaTJVTQpCT3FlUXIwdUhJT0tEREM4TENGeEFJa1BIeTBxSjgxRTJNaTRCRk1HcjVsMks3TTVjTUdyWHBYMVN6ZXVtTDdkCnV6Z2swM2VuaDhJQU1WVXQraHk0NzJmaHh4Z21waGx1Sy96UGxSOUFUeEJMeHpjbllyV2Z6TnZYSm9ZT2FCZGIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=","key.pem":"LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBM1JCcWVPazJZY0NMaElYcFd2YmUycGdXdGxkVmsxTnhwQjM2ajVCUWlaWC9La1M0Ck4yMWo3THVpNnlRZWgxQnZOOCtvMjZrUlBqS3UvMjNIbmM5cXBrMmJ5UUY4K3lWU1hlSWZpNHRtaHlWTUw0WGcKd2g3YTI0U0J6YzEyOGd6WElsRUorSlhNWHI0Tzd4ZkF6TXJ5d0Q1MklCbm9oNURZRkR3UlVsd1VZaHhGTTNOYQpNc0RuVjVjTEVtcjlEMkJGUlRRZmZ3T1htYkZBaTA3U2lYYjBWTjg4QUFiUjhxS1FiN2xyNG96YklPVGpaQVE4CmhFY2c0bkhDQmxnTGhKRkRoNFRscHNtaVFPUkh1LzBQZUZPamtKV080bnh3bzkvYXk4aGlTbGJoUjdTU1V2c2UKUEx6Z2dwSmhEUEpZTzBrem5ibEdDTGdCOWF4S2xhLzRLaDBzUlFJREFRQUJBb0lCQVFDcHF2dk5LVkZ2M1ZRMwp0bi9RTFVJR0RFMENUaTJFRWJ0YTl4ZGtNS05mdGh4TjJNaDY0aDZiaDdnWE9YV2s3WHN2SHRhL0lSZjI0UGVuClhCNmxaSmk2WXo1NkhBWk15K3hYMmtIVDNING9vOXZCYmNOL3VpYkg3UCtqY1ZzbGsrMWFqVkJWMXNNd3hEYTYKRTBVSzZZay9PN0YyR2V4NmdCVVlFckpJd0J0MDRFaWZHTStwblNPL3gxN01obzN0VW9hdzgvV096UlU2Mlorbwp0Mm9WVHlMTnU3R3BhWVVRa3hOOHZML1IwdWo4bXY3Z2VyMWNBMmwrUDJVb1dzZmM3MG42dHNyRVJaRmd6VmNCClhCT3FpOTBzRUxoNEZ0M0xPZjN0Z2NBYXBtSHU3UDNDMnlEeEd3YTRtNTZ5RmJ6RTNMN29XK3FLOUhsV1hVT0sKYjkrQWZyTlJBb0dCQU85RmcwNkE4QjJCSDVuSnhyTEZkRTl5bHN1UEZ4RWhlMldzR1QyMjAxM3B0MWluMVZnLwpuMXRPMzJYZlgrcFZ1dUpaTnpRTVpSQWE5YnJaZVIxeTl6NEh0YW16dGJZRjRVK3lkbmgrbFlHVlNESU5FWW5ECk9ZRTRyRjdERTNabmNqRkJNcGpwUEpia0JHcU1CN3VEanF3M3hOckdrM1BRQmZMWmEvRW5NRHkzQW9HQkFPeUYKQnNCQm84VXhCZFVqdWVDY25PNVZhNjdDaUdlNnhCcFY5aHlWN1BvZ2ZhaWxyZTVCOXZPb2prOU8xUENOUVlVZwphYWd6elc5MGhZNzcyWFBjclBDQUI0Nkx6UHpVbVFjUlkzZWNjZTlLZkErU1RSYWdYRjBVS05TK2RoQ2FSa09YCmtoQ0lML29LMks0RlhNanI5WXdvQ0R1V0JhdkEyRVZWWEJuUitWcmpBb0dCQU9aYkh5SmFRbEcxZWEzK3M3eHoKR3hwTjhOM0RRZXJ0T0RiWGJHbWM5WHVKd2ttcE0xM0Z5dThHVFU5dnNaRVN2bHlpbGVJWE9NazdtMjRyWjA0eAoyOVN0YVhrYkdndEhOL2Naa3JOSTh6a1Jkck14SDd4bzVwa0E3ZnBCaHlCTVVZVVlCdFZ1WHpYS0NuSmxwQ0FrCmRSeGFpTHd6eDh3TTcxMHhjNWwxS0J5YkFvR0FRTVg5bjFGYXBIcFVlcGFhSlNVKzVSYUhzd2liaXF6Zlg4Y0MKNjdremVSekV6UmJ5bHptQmhDRTVPQWNDMGc0ZFQzUWMrMitVWjEybDVnNmE4dHdRa0p5L2RRNWNTVEYvNXl1Zgo3Zlh1VGZZOEc1ZVpmUVRWeHJmcXByaXlaTUdiVkkrQjlQMFhCb2RKNS82WDluNklkS1hSKzErT2xnYnVNNjY0CjFtbG12TGtDZ1lCS2xHV09QRUpkUzRYQ3J6N1FaT0JGOU5YRUFSSmExa2I0a3BOOTY0VEdCRFVqZTliMzVmRDgKVlh1TVdOeVptbExsT1BFaTJONGVVb0Z5cHQrVXpPeEp1OVNTMzJCOEJsVWxFeVRJaE1xUkRwZkQzWTl2Uy9oOQpLMFk3enRlRlYxY0tIS1ljaFhSM3pmNU4wdEZ3SWs0RU1ReVpIYzd5SW9aMjBuK2xHTDQ0OUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"admission-controller-certs","namespace":"test"}}
#  creationTimestamp: "2019-10-26T10:40:45Z"
#  name: admission-controller-certs
#  namespace: test
#  resourceVersion: "1187"
#  selfLink: /api/v1/namespaces/test/secrets/admission-controller-certs
#  uid: 10ba5f7b-f7dd-11e9-9d2f-025000000001
#type: Opaque

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-controller-cr
  namespace: test
  labels:
    app: admission-webhook
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
  - apiGroups: ["pingcap.com"]
    resources: ["tidbclusters"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["service"]
    verbs: ["create","delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-controller-sa
  namespace: test
  labels:
    app: admission-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-controller-crb
  namespace: test
  labels:
    app: admission-controller
subjects:
  - kind: ServiceAccount
    name: admission-controller-sa
    namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-controller-cr
---
apiVersion: v1
kind: Service
metadata:
  name: admission-controller-svc
  namespace: test
  labels:
    app: admission-controller
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller
  namespace: test
  labels:
    app: admission-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-controller
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      serviceAccountName: admission-controller-sa
      containers:
        - name: admission-controller
          image: yisa/webhook:0.1.4
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/tidb-admission-controller
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -v=2
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-controller-certs
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutation-admission-contorller-cfg
  labels:
    app: admission-controller
webhooks:
  - name: create-pod-admission-controller.pingcap.net
    failurePolicy: Fail
    clientConfig:
      service:
        name: admission-controller-svc
        namespace: test
        path: "/pods"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVWnV1cUw5WUNjdlhUcVBKckRjWEJYNjB1RURJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekFlRncweE9URXdNall4TURNMk1EQmFGdzB5TURFdwpNalV4TURNMk1EQmFNQ3d4S2pBb0JnTlZCQU1USVdGa2JXbHpjMmx2YmkxamIyNTBjbTlzYkdWeUxYTjJZeTUwClpYTjBMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjBRYW5qcE5tSEEKaTRTRjZWcjIzdHFZRnJaWFZaTlRjYVFkK28rUVVJbVYveXBFdURkdFkreTdvdXNrSG9kUWJ6ZlBxTnVwRVQ0eQpydjl0eDUzUGFxWk5tOGtCZlBzbFVsM2lINHVMWm9jbFRDK0Y0TUllMnR1RWdjM05kdklNMXlKUkNmaVZ6RjYrCkR1OFh3TXpLOHNBK2RpQVo2SWVRMkJROEVWSmNGR0ljUlROeldqTEE1MWVYQ3hKcS9ROWdSVVUwSDM4RGw1bXgKUUl0TzBvbDI5RlRmUEFBRzBmS2lrRys1YStLTTJ5RGs0MlFFUElSSElPSnh3Z1pZQzRTUlE0ZUU1YWJKb2tEawpSN3Y5RDNoVG81Q1ZqdUo4Y0tQZjJzdklZa3BXNFVlMGtsTDdIank4NElLU1lRenlXRHRKTTUyNVJnaTRBZldzClNwV3YrQ29kTEVVQ0F3RUFBYU9CdkRDQnVUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVU1ZGZ2R2VKZ0ZTZWtGUWRabURyVwo0WktsNDBJd1pRWURWUjBSQkY0d1hJSVlZV1J0YVhOemFXOXVMV052Ym5SeWIyeHNaWEl0YzNaamdoMWhaRzFwCmMzTnBiMjR0WTI5dWRISnZiR3hsY2kxemRtTXVkR1Z6ZElJaFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXQKYzNaakxuUmxjM1F1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkZTbjNnWmxkYUQ4amhORDQxV2tPMgpLR1BJdE9iS0xyeENvWHhQVGNqRDlkQlkzdkRHOUJrUitmeTFxRE9DNEhBQkNlMzNyNjlNOEtmOHRubVQvTjBDCmhjVTFmaUYrbXFoYjNiVUJOVytUa3FrR0NQMUxKSzk3USt2aWNadHJXVEt6ajRMMVRQSjRyZTJUR2xCS1VEdDMKQjI5cWF0b25EODFPQ1VXRDVlc2JwZ0RGQzNmeTZHZkk0SldXR0FZRXNhSnEyclBZTVdJcEVidlJubDhTaTJVTQpCT3FlUXIwdUhJT0tEREM4TENGeEFJa1BIeTBxSjgxRTJNaTRCRk1HcjVsMks3TTVjTUdyWHBYMVN6ZXVtTDdkCnV6Z2swM2VuaDhJQU1WVXQraHk0NzJmaHh4Z21waGx1Sy96UGxSOUFUeEJMeHpjbllyV2Z6TnZYSm9ZT2FCZGIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [ "" ]
        apiVersions: ["v1"]
        resources: ["pods"]
##  - name: delete-pod-admission-controller.pingcap.net
#    failurePolicy: Fail
#    clientConfig:
#      service:
#        name: admission-controller-svc
#        namespace: test
#        path: "/pods"
#      caBundle: ${CA_BUNDLE}
#    rules:
#      - operations: [ "DELETE" ]
#        apiGroups: [ "" ]
#        apiVersions: ["v1"]
#        resources: ["pods"]
